### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by muan** [jlord/sheetsee-calendar#1]
@jlord you take this one!!!! :heart:

Also I always think it'll help to have some sort of CSS guide, like, if I hate the party color theme, instead reading the DOMs to understand what's what, if we can have a chart like

![image](https://f.cloud.github.com/assets/1153134/2432168/818021fc-ad57-11e3-8ff8-8b483afc2720.png)

I don't know, I have never seen anything like this so it might be stupid, what do you think?

**Comment by jlord** [comment]
No, this would be SO AWESOME! I'm so into doing whatever -- trying anything -- in the pursuit of better-enabling documentation! Also, it's a great idea!

**Comment by muan** [comment]
Done @jlord? Good for now?

**Comment by jlord** [comment]
:palm_tree:
