### ISSUE TITLE
Crossing the year line

### ISSUE THREAD

**Issue by muan** [jlord/sheetsee-calendar#10]
This seems problematic when `date.getMonth() + 1` becomes more than 11. https://github.com/jlord/sheetsee-calendar/blob/gh-pages/js/table.js#L92
Need to test it out and make sure it performs alright all year round.

**Comment by muan** [comment]
Just works™

**Comment by jlord** [comment]
LOL. 

You rocked a bunch of stuff today! I just reopened my email and saw them :boom:
