### ISSUE TITLE
placement in carousel

### ISSUE THREAD

**Issue by Showcase-Joz** [jlord/sheetsee-calendar#14]
ok so i've altered the css quite extensively, a little of the js too. 

but now i am wanting to show this element in a carousel......any ideas on this pls ladies?

![clipular](https://cloud.githubusercontent.com/assets/3405708/3174590/47e96f36-ebf3-11e3-9321-647bee1896ea.png)

**Comment by jlord** [comment]
Hi @Showcase-Joz!

I'm not familiar with Bootstrap and unfortunately I can't help in regards to if it works inside of a carousel. You may have to pave that path! :smile: 

In your email you also mentioned having a week and day view, those are options out of the scope of this repository but you should go wild on your fork and make it the calendar you want! Making the day and week view will involve rewriting the table.js and I imagine passing in options to `generateCalendar` to specify which view. Alternatively you could write a week and day view as modules in their own .js files. Good luck! :tada:
