### ISSUE TITLE
Calendar Key?

### ISSUE THREAD

**Issue by Hipomenes** [jlord/sheetsee-calendar#20]
Hi! I've been trying to set up the calendar, but the Google Calendar code I get does not resemble the one you mention. Any suggestions?

**Comment by jlord** [comment]
Hi! This doesn't work with Google Calendar, but I can see how that's confusing. Instead, it _makes a calendar_  by styling in HTML/CSS dates that are stored in a Google Spreadsheet.

**Comment by xihajun** [comment]
it may be doable if we sync calendar to the sheet I guess?
