### ISSUE TITLE
Expose more information

### ISSUE THREAD

**Issue by muan** [jlord/sheetsee-calendar#3]
- [x] Site Title
- [x] Current Day
- [x] Location
- [ ] ~~Time of Event~~

**Comment by jlord** [comment]
> Location 

I would **love** to also have a map but here are the hurdles:
- You can't use Google's Geocoding API without using a Google Map
- You can't really get an API key and then share it (by telling people to fork) with everyone. 
- You could have people enter in lat,long coordinates, as I've done before, but I wish it were easier.
- MapBox has a Geocoding API/Google Spreadsheet extension that we could use. It, however, doesn't get street level, it gets state-level at best I think, but perhaps that's good enough for this as most events will have a link with more details?

Other location-y things:
- We could add an address  column to the spreadsheet and assemble a Google maps query string from that.
- Filtering by location would be awesome. I imagine we could do this the same way I use an input box to filter traditional tables on the other sheetsee pages -- listen to keypress, filter the data, rebuild table... 

> Time of Event
- My gut feeling is that this is isn't a critical feature to have. I imagine there might not be a ton of conflicting events and most events will link out to the event page with details anyways -- but
- I suppose, though, that we could have a field for time and then create in this calendar a querystring to add the event to the user's Google Calendar..
- We could display the time and sort events on the day by time.

> Site Title
- Tabletop doesn't return the spreadsheet name so I think that if we just add an `<h1>` in the HTML people can edit it themselves easily enough.

**Comment by jlord** [comment]
- Current Day

Doing some highlight of the current day shouldn't be too hard (?) and would be nice.

**Comment by muan** [comment]
> MapBox has a Geocoding API/Google Spreadsheet extension that we could use. It, however, doesn't get street level, it gets state-level at best I think, but perhaps that's good enough for this as most events will have a link with more details?

I think that is plenty good enough! Would you want to work on that?

> My gut feeling is that this is isn't a critical feature to have. 

Agree.

>  we just add an # in the HTML people can edit it themselves easily enough.

:+1:

>  highlight of the current day shouldn't be too hard

:+1: on it.

**Comment by jlord** [comment]
> Would you want to work on that?

:+1: I'll add the MapBox stuff

**Comment by jlord** [comment]
I added the Mapbox tool --

![screen shot 2014-03-17 at 5 56 16 pm](https://f.cloud.github.com/assets/1305617/2443546/34857b4a-ae38-11e3-82a7-f78895f7c2b2.png)

It needs to be run whenever a new address is added though.

You run it by clicking the new Geo menu on the spreadsheet, with the location cell highlighted, then clicking "Geocode" 

I'll add about this to the readme!

**Comment by jlord** [comment]
I'm checking 'location' on this list (just edited the orig. issue with checkboxes) and going to open a new one for adding maps.

**Comment by muan** [comment]
Can you do the mapbox part too? I am not familiar with `mapbox.js`. Or maybe we can pair on it tomorrow?

**Comment by jlord** [comment]
Yeahhhh!!!!

**Comment by muan** [comment]
Looks like this is done? Is it possible to change color/theme of the map?
And so sorry for doing this.. but I started to think that, since there is a sheetsee-maps, this should probably only contain the calendar... what do you think?

**Comment by jlord** [comment]
>  since there is a sheetsee-maps, this should probably only contain the calendar 

Like this project/repo should just contain a calendar and not a map? Is that what you're asking?

**Comment by muan** [comment]
yupyupyup

**Comment by jlord** [comment]
Nope! I think it should have both. Because it's not about making an example of a thing that Sheetsee can do, it's about making a forkable project that may be of use to people.

So the use-case is _event page_ and I think that people may want a map _and_ a calendar (like how Hack Spots has a both a table and map). Since deleting the map is easier than creating it, I'd rather have it by default. 

However.

It may be more likely that people won't want to add their own lat/long or will have events that all occur in one city (therefore the Mapbox geocoding would make for a very dull map). So maybe maintaining the map is more trouble than it's worth for the users?

Maybe we can move the map version to another branch and let people know it's there if they want it, but keep `gh-pages` mapless?

**Comment by jlord** [comment]
Is it possible to change color/theme of the map?
- Totally, people can create their own tiles: [mapbox.com/editor](https://www.mapbox.com/editor/#welcome)
- Or grab existing tiles from [Mapbox's examples](https://www.mapbox.com/mapbox.js/example/v1.0.0/low-bandwidth/)
- Or make tiles in Mapbox's [Tilemill](https://www.mapbox.com/tilemill/)
- You can change the marker color by adding a `hexcolor` key/value to each row either in the spreadsheet or in JS (as I did in this repo).

**Comment by muan** [comment]
I believe this is done.
