### ISSUE TITLE
Month pagination

### ISSUE THREAD

**Issue by muan** [jlord/sheetsee-calendar#4]
This will be fun.

![](http://25.media.tumblr.com/d4a20fcafefa6a7a0e2f38b43977a7b6/tumblr_n2ig31WpfO1qdlh1io1_400.gif)

**Comment by jlord** [comment]
lol :dog: 

I don't even want to have you look at my code and I don't know of it's even helpful, but I have pagination built into the normal [sheetsee tables](https://github.com/jlord/sheetsee-tables/blob/master/index.js), maybe some of that is useful.
